ParticleGroups:
  - File: ../data/cylinder.xyz
    Mass: 1.0
    Velocity: [0.0, 0.0, 0.0]
    YoungModulus: 1.4e5
    PoissonRatio: 0.2
    HardeningCoefficient: 5
    CriticalCompression: 2.5e-2 
    CriticalStretch: 7.5e-3
    ConstitutiveModel: FixedCorotated
  - File: ../data/dragon.xyz
    Mass: 1.0
    Velocity: [0.0, -1.0, 0.0]
    YoungModulus: 1.4e5
    PoissonRatio: 0.2
    HardeningCoefficient: 1
    CriticalCompression: 0.1e-2
    CriticalStretch: 1.0e-3
    ConstitutiveModel: FixedCorotated
Grid:
  Origin: [0.0, 0.0, 0.0]
  Resolution: [800, 800, 800]
  Stride: 5e-3 
  BoundaryFrictionCoefficient: 0.9
Transfer:
  BlendCoefficient: 0.90 
Interpolation:
  Type: CubicBSpline
Simulate:
  deltaTime: 1e-3
Render:
  Offline: true 
  ParticleFragmentShader: ../shader/snow.frag